services:
  - type: web
    name: jarvis-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ls -l && python -m uvicorn main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
